### ISSUE TITLE
[Client] Look for a way to share variables between BitBake recipes

### ISSUE THREAD

**Issue by javiroman** [comodoo/meta-comodoo#1]
Given that I install all executable scripts in the same place, it would be nice to define this path (and any other I might need) in one place and share among all recipes, like BitBake already does with `bindir` or `datadir`.

**Comment by indisoluble** [comment]
Also, it would be nice to share among the python scripts, the paths to the different common resources, instead of writing them over and over.

**Comment by indisoluble** [comment]
On issue #10, I added `collectd` to our _Yocto image_; it is configured to use `comodoo-pos` as **hostname** and this is name is used to compose the path to store the CSVs: `/var/lib/collectd/csv/comodoo-pos/`. In turn, in issue #11, I added `rsyslog` to our image and it also configured with the path above. It would nice to specify this name in only one place and share it between both configuration instead of _hard-coding_ it in both configuration files.
