### ISSUE TITLE
[Client] Add collectd into meta-comodoo

### ISSUE THREAD

**Issue by javiroman** [comodoo/meta-comodoo#10]
Add Collectd for metrics gathering from device.

**Comment by javiroman** [comment]
The sample file used in #11 configuration, here: `/etc/collectd.conf`

```
Hostname    "producer-node1"
FQDNLookup   true
BaseDir     "/var/lib/collectd"
PIDFile     "/var/run/collectd.pid"
PluginDir   "/usr/lib64/collectd"
TypesDB     "/usr/share/collectd/types.db"

Interval     1
ReadThreads     5
WriteThreads    5

LoadPlugin logfile
<Plugin logfile>
        LogLevel info
        File STDOUT
        Timestamp true
        PrintSeverity false
</Plugin>

LoadPlugin csv
#LoadPlugin syslog

LoadPlugin cpu
LoadPlugin cpufreq
LoadPlugin cpusleep
LoadPlugin disk
LoadPlugin interface
LoadPlugin load
LoadPlugin lvm
LoadPlugin memory
LoadPlugin sensors
LoadPlugin statsd
LoadPlugin swap

<Plugin csv>
        DataDir "/var/lib/collectd/csv"
        StoreRates true
</Plugin>

#<Plugin "syslog">
#  LogLevel "info"
#  NotifyLevel "OKAY"
#</Plugin>

<Plugin disk>
        Disk "/^[hs]d[a-f][0-9]?$/"
        IgnoreSelected false
        UdevNameAttr "DEVNAME"
</Plugin>

Include "/etc/collectd.d"
```

**Comment by indisoluble** [comment]
Changes to complete this issue will be done in branch [krogoth-syslog](https://github.com/comodoo/meta-comodoo/tree/krogoth-syslog).

**Comment by indisoluble** [comment]
@javiroman The version of collectd provided by [meta-openembedded](http://cgit.openembedded.org/cgit.cgi/meta-openembedded/tree/meta-oe/recipes-extended/collectd/collectd_5.5.0.bb?h=master) is [5.5.0](https://github.com/collectd/collectd/releases/tag/collectd-5.5.0) and it does not include the plugin called `cpusleepcpusleep`. Is this a problem??

**Comment by javiroman** [comment]
@indisoluble no problem with this collectd version. We'll disable this metrics.

**Comment by indisoluble** [comment]
In that case, with the changes I made in commit 8e2f626f07f2a9369fbb693c1b65aff8423d5c23, we are already generating a _Yocto image_ with the following configuration for `collectd`: [collectd.conf](https://github.com/comodoo/meta-comodoo/files/604196/collectd.conf.txt).

@javiroman Whenever you have a  moment, have a look and confirm if this configuration is alright. There are some minor differences:

- `Hostname    "comodoo-pos"` instead of `Hostname    "producer-node1"`
- `FQDNLookup   false` instead of `FQDNLookup   true`
- `PIDFile`, `PluginDir` & `TypesDB` remain commented
- `LoadPlugin cpusleep` not included

**Comment by indisoluble** [comment]
So far, it looks like this configuration is alright; @javiroman if you think there is a problem, please open a new issue and link it to this one.
