### ISSUE TITLE
[Client] Replace 'WebPy' with 'CherryPy'

### ISSUE THREAD

**Issue by javiroman** [comodoo/meta-comodoo#5]
On issue #18, I introduced the web framework [CherryPy](http://cherrypy.org/). IMHO, this framework is better maintained and it is easier to use than [WebPy](http://webpy.org/) which is currently used by `eca-web`.

Rewrite `eca-web` to use `CherryPy` and remove dependency of `WebPy`.

**Comment by indisoluble** [comment]
To use `CherryPy` instead of `WebPy`, I have to write a new `eca-web`. What is more, our final objective is to centralize the entire configuration process in a single web server.  Although the current configuration process is quite simple, I think the better approach to this task is to create a new repo to work in this task and only add to our _Yocto project_ a recipe to import the code from the repository ... as we do with `eca-web`.

Once I create the repo, I will attach a link in this issue and close it.

**Comment by indisoluble** [comment]
As promised: https://github.com/comodoo/comodoo-pos-wizard.
