### ISSUE TITLE
[Client] Mount root partition as read-only

### ISSUE THREAD

**Issue by javiroman** [comodoo/meta-comodoo#9]
As mentioned in [Odoo documentation](https://github.com/odoo/documentation-user/blob/9.0/point_of_sale/overview/setup.rst):

> The root partition on the POSBox is mounted read-only, ensuring that we don't wear out the SD card by writing to it too much. It also ensures that the filesystem cannot be corrupted by cutting the power to the POSBox.

This is good idea that we should apply too.

**Comment by indisoluble** [comment]
This is still a good idea but we are far from being able to implement it. First we need to clearly specify the design of our POS: which information need to be writable and/or saved between bootings, how we intend to partition the disk, ...; also this issue is influenced by the updating mechanism we still have to choose.

I am going to close this issue now and, whenever we are in a better position to accomplish this task, we will create a new one.
